### ISSUE TITLE
faction hangar clean unload fail

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/TSTSSES-ModRepository#176]
found this in the pain vortex

![image](https://github.com/user-attachments/assets/9f62bfa4-9504-41ca-9d00-92f35b6c1ec0)

**Comment by InvalidArgument3** [comment]
```
2024-10-24 05:02:52.518 - Thread:   1 ->  Exception occurred: VRage.Game.ModAPI.ModCrashedException: Mod crashed! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomHangar.Session.UnloadData()
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   --- End of inner exception stack trace ---
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.EndLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2024-10-24 05:02:52.518 - Thread:   1 ->  InnerException: 
2024-10-24 05:02:52.518 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomHangar.Session.UnloadData()
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
2024-10-24 05:02:52.518 - Thread:   1 ->  Showing message
2024-10-24 05:02:52.518 - Thread:   1 ->  MyInitializer.OnCrash
2024-10-24 05:02:52.518 - Thread:   1 ->  var exception = VRage.Game.ModAPI.ModCrashedException: Mod crashed! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomHangar.Session.UnloadData()
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   --- End of inner exception stack trace ---
   at Sandbox.Game.World.MySession.UnloadDataComponents(Boolean beforeLoadWorld)
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.EndLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
```
