### ISSUE TITLE
dynast world serializing death

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/TSTSSES-ModRepository#179]
seems to dropkick the sbsb5 requiring the world to be loaded again

quick fix: nuke old persistence code

2024-10-23 12:15:39.337 - Thread:   1 ->  Exception occurred: ProtoBuf.ProtoException: No parameterless constructor found for VRage.ObjectBuilders.MyObjectBuilder_Base
   at ProtoBuf.Meta.TypeModel.ThrowCannotCreateInstance(Type type)
   at proto_1782(ProtoReader , State& , Object )
   at ProtoBuf.ProtoReader.ReadTypedObject(ProtoReader reader, State& state, Object value, Int32 key, Type type)
   at proto_1409(ProtoReader , State& , Object )
   at ProtoBuf.ProtoReader.ReadTypedObject(ProtoReader reader, State& state, Object value, Int32 key, Type type)
   at ProtoBuf.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader, State& state)
   at proto_1782(ProtoReader , State& , Object )
   at ProtoBuf.Meta.TypeModel.DeserializeAny(ProtoReader reader, State& state, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at VRage.ObjectBuilders.Private.MyObjectBuilderSerializerKeen.DeserializePB(Stream reader, MyObjectBuilder_Base& objectBuilder, Type builderType)
2024-10-23 12:15:39.337 - Thread:   1 ->  Failed to deserialize file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Saves\76561198071098415\emptyroid/SANDBOX_0_0_0_.sbsB5'
2024-10-23 12:15:39.337 - Thread:   1 ->  Incorrect save data
2024-10-23 12:15:39.337 - Thread:   1 ->  Error: Error during loading session:Sandbox.Game.Screens.MyLoadingNeedXMLException
   at Sandbox.Game.World.MySession.Load_Patch1(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
2024-10-23 12:15:39.337 - Thread:   1 ->  MyGuiScreenGamePlay.UnloadData - START

2024-10-23 12:15:46.277 - Thread:   1 ->  ERROR: Exception during objectbuilder read! (pb): MyObjectBuilder_Sector
2024-10-23 12:15:46.277 - Thread:   1 ->  Exception occurred: ProtoBuf.ProtoException: No parameterless constructor found for VRage.ObjectBuilders.MyObjectBuilder_Base
   at ProtoBuf.Meta.TypeModel.ThrowCannotCreateInstance(Type type)
   at proto_1782(ProtoReader , State& , Object )
   at ProtoBuf.ProtoReader.ReadTypedObject(ProtoReader reader, State& state, Object value, Int32 key, Type type)
   at proto_1409(ProtoReader , State& , Object )
   at ProtoBuf.ProtoReader.ReadTypedObject(ProtoReader reader, State& state, Object value, Int32 key, Type type)
   at ProtoBuf.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader, State& state)
   at proto_1782(ProtoReader , State& , Object )
   at ProtoBuf.Meta.TypeModel.DeserializeAny(ProtoReader reader, State& state, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at VRage.ObjectBuilders.Private.MyObjectBuilderSerializerKeen.DeserializePB(Stream reader, MyObjectBuilder_Base& objectBuilder, Type builderType)
2024-10-23 12:15:46.277 - Thread:   1 ->  Failed to deserialize file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Saves\76561198071098415\emptyroid/SANDBOX_0_0_0_.sbsB5'

**Comment by InvalidArgument3** [comment]
was unable to find this but 100% reproducable by saving the world and reloading it with at least 1 roid entity present
something about that entity the game doesn't like to think about
will need to make the networking .cs less annoying to look at before solving this, going to need like 3 different managers in a big refactor
